# Dependabot configuration for Vidalytics
# Automatically creates pull requests for dependency updates

version: 2
updates:
  # Backend Python dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "your-team/backend-maintainers"
    assignees:
      - "your-team/backend-maintainers"
    labels:
      - "dependencies"
      - "backend"
      - "python"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Frontend Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/frontend-nuxt4"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "your-team/frontend-maintainers"
    assignees:
      - "your-team/frontend-maintainers"
    labels:
      - "dependencies"
      - "frontend"
      - "javascript"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      build-tools:
        patterns:
          - "vite*"
          - "@vitejs/*"
          - "typescript"
          - "eslint*"
          - "@typescript-eslint/*"
        update-types:
          - "minor"
          - "patch"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    reviewers:
      - "your-team/devops-maintainers"
    assignees:
      - "your-team/devops-maintainers"
    labels:
      - "dependencies"
      - "docker"
      - "backend"
    commit-message:
      prefix: "docker"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/frontend-nuxt4"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    reviewers:
      - "your-team/devops-maintainers"
    assignees:
      - "your-team/devops-maintainers"
    labels:
      - "dependencies"
      - "docker"
      - "frontend"
    commit-message:
      prefix: "docker"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    reviewers:
      - "your-team/devops-maintainers"
    assignees:
      - "your-team/devops-maintainers"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
    commit-message:
      prefix: "ci"
      include: "scope"
