"""
Application Constants for CreatorMate
Centralized location for magic numbers and configuration values
"""

# Rate Limiting
DEFAULT_RATE_LIMIT_PER_MINUTE = 60
DEFAULT_RATE_LIMIT_BURST = 10
AUTH_RATE_LIMIT_PER_MINUTE = 10

# Session & JWT
DEFAULT_SESSION_TIMEOUT_HOURS = 8
DEFAULT_JWT_EXPIRY_HOURS = 4
TOKEN_BLACKLIST_CLEANUP_HOURS = 24

# Cache TTL (seconds)
CACHE_TTL_SHORT = 1800      # 30 minutes
CACHE_TTL_MEDIUM = 7200     # 2 hours
CACHE_TTL_LONG = 14400      # 4 hours
CACHE_TTL_VERY_LONG = 43200 # 12 hours

# Agent System
MAX_CONVERSATION_HISTORY = 20
MAX_INSIGHTS_PER_USER = 5
MAX_RETRY_ATTEMPTS = 3
REQUEST_TIMEOUT_SECONDS = 30

# YouTube API
YOUTUBE_API_QUOTA_LIMIT_PER_DAY = 10000
YOUTUBE_MAX_RESULTS_PER_REQUEST = 50
YOUTUBE_MAX_CONCURRENT_REQUESTS = 5

# Database
MAX_CONNECTION_POOL_SIZE = 20
CONNECTION_TIMEOUT_SECONDS = 30
QUERY_TIMEOUT_SECONDS = 60

# File Upload
MAX_FILE_SIZE_MB = 10
ALLOWED_FILE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.gif', '.webp']

# Pagination
DEFAULT_PAGE_SIZE = 25
MAX_PAGE_SIZE = 100

# Response Formats
SUCCESS_STATUS = "success"
ERROR_STATUS = "error"
PENDING_STATUS = "pending"

# Security
MIN_PASSWORD_LENGTH = 8
MAX_LOGIN_ATTEMPTS = 5
LOCKOUT_DURATION_MINUTES = 15

# AI Models
DEFAULT_TEMPERATURE = 0.7
MAX_TOKENS_PER_REQUEST = 4000
CONTEXT_WINDOW_SIZE = 8000

# Health Check
HEALTH_CHECK_TIMEOUT_SECONDS = 5
SYSTEM_HEALTH_CACHE_TTL = 300  # 5 minutes