[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "bash /app/start-railway.sh"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHONPATH = "/app"
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "INFO"
HOST = "0.0.0.0"
WORKERS = "1"
