[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "cd /app && uvicorn railway_main:app --host 0.0.0.0 --port ${PORT:-8888}"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHONPATH = "/app"
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "INFO"
HOST = "0.0.0.0"
WORKERS = "1"
