<template>
  <div v-if="show" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
    <div class="bg-forest-900 border border-forest-600 rounded-lg w-full max-w-4xl max-h-[90vh] overflow-hidden">
      <!-- Modal Header -->
      <div class="flex items-center justify-between p-6 border-b border-forest-600">
        <div class="flex items-center space-x-4">
          <img src="/Agent2.png" alt="Research Agent" class="w-10 h-10 rounded-lg border-2 border-orange-400" />
          <div>
            <h2 class="text-xl font-bold text-white">{{ note?.title || 'Research Results' }}</h2>
            <p class="text-gray-400 text-sm">Generated by Research Agent</p>
          </div>
        </div>
        <button @click="$emit('close')" class="text-gray-400 hover:text-white transition-colors">
          <svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
          </svg>
        </button>
      </div>

      <!-- Modal Content -->
      <div class="flex h-[calc(90vh-140px)]">
        <!-- Research Content -->
        <div class="flex-1 p-6 overflow-y-auto">
          <div class="prose prose-invert max-w-none">
            <div class="whitespace-pre-wrap text-gray-200 leading-relaxed">{{ note?.content }}</div>
          </div>
        </div>

        <!-- Action Panel -->
        <div class="w-80 bg-forest-800 border-l border-forest-600 p-6 overflow-y-auto">
          <h3 class="text-lg font-semibold text-white mb-4">Save Options</h3>
          
          <!-- Save as Task -->
          <div class="mb-6">
            <button 
              @click="showTaskForm = !showTaskForm"
              class="w-full bg-blue-600 hover:bg-blue-700 text-white px-4 py-3 rounded-lg transition-colors flex items-center justify-center space-x-2"
            >
              <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"/>
              </svg>
              <span>Save as Task</span>
            </button>
            
            <div v-if="showTaskForm" class="mt-4 space-y-3">
              <input 
                v-model="taskTitle"
                placeholder="Task title..."
                class="w-full bg-forest-700 border border-forest-500 rounded-lg px-3 py-2 text-white placeholder-gray-400 focus:outline-none focus:border-blue-500"
              />
              <textarea 
                v-model="taskDescription"
                placeholder="Task description..."
                rows="3"
                class="w-full bg-forest-700 border border-forest-500 rounded-lg px-3 py-2 text-white placeholder-gray-400 focus:outline-none focus:border-blue-500 resize-none"
              ></textarea>
              <select 
                v-model="taskPriority"
                class="w-full bg-forest-700 border border-forest-500 rounded-lg px-3 py-2 text-white focus:outline-none focus:border-blue-500"
              >
                <option value="low">Low Priority</option>
                <option value="medium">Medium Priority</option>
                <option value="high">High Priority</option>
                <option value="urgent">Urgent</option>
              </select>
              <button 
                @click="saveAsTask"
                class="w-full bg-green-600 hover:bg-green-700 text-white px-3 py-2 rounded-lg transition-colors"
              >
                Create Task
              </button>
            </div>
          </div>

          <!-- Save as Goal -->
          <div class="mb-6">
            <button 
              @click="showGoalForm = !showGoalForm"
              class="w-full bg-purple-600 hover:bg-purple-700 text-white px-4 py-3 rounded-lg transition-colors flex items-center justify-center space-x-2"
            >
              <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/>
              </svg>
              <span>Save as Goal</span>
            </button>
            
            <div v-if="showGoalForm" class="mt-4 space-y-3">
              <input 
                v-model="goalTitle"
                placeholder="Goal title..."
                class="w-full bg-forest-700 border border-forest-500 rounded-lg px-3 py-2 text-white placeholder-gray-400 focus:outline-none focus:border-blue-500"
              />
              <textarea 
                v-model="goalDescription"
                placeholder="Goal description..."
                rows="3"
                class="w-full bg-forest-700 border border-forest-500 rounded-lg px-3 py-2 text-white placeholder-gray-400 focus:outline-none focus:border-blue-500 resize-none"
              ></textarea>
              <input 
                v-model="goalTarget"
                placeholder="Target (e.g., 10K views, 100 subscribers)"
                class="w-full bg-forest-700 border border-forest-500 rounded-lg px-3 py-2 text-white placeholder-gray-400 focus:outline-none focus:border-blue-500"
              />
              <button 
                @click="saveAsGoal"
                class="w-full bg-green-600 hover:bg-green-700 text-white px-3 py-2 rounded-lg transition-colors"
              >
                Create Goal
              </button>
            </div>
          </div>

          <!-- Additional Actions -->
          <div class="space-y-3">
            <button 
              @click="copyToClipboard"
              class="w-full bg-gray-600 hover:bg-gray-700 text-white px-4 py-2 rounded-lg transition-colors flex items-center justify-center space-x-2"
            >
              <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"/>
              </svg>
              <span>Copy to Clipboard</span>
            </button>
            
            <button 
              @click="exportToPDF"
              class="w-full bg-gray-600 hover:bg-gray-700 text-white px-4 py-2 rounded-lg transition-colors flex items-center justify-center space-x-2"
            >
              <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>
              </svg>
              <span>Export as PDF</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'

interface Props {
  show: boolean
  note: any
}

interface Emits {
  (e: 'close'): void
  (e: 'saveAsTask', data: any): void
  (e: 'saveAsGoal', data: any): void
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

// Form states
const showTaskForm = ref(false)
const showGoalForm = ref(false)

// Task form data
const taskTitle = ref('')
const taskDescription = ref('')
const taskPriority = ref('medium')

// Goal form data
const goalTitle = ref('')
const goalDescription = ref('')
const goalTarget = ref('')

// Watch for note changes to populate forms
watch(() => props.note, (newNote) => {
  if (newNote) {
    taskTitle.value = `Research: ${newNote.title}`
    taskDescription.value = newNote.content
    goalTitle.value = `Goal: ${newNote.title}`
    goalDescription.value = newNote.content
  }
}, { immediate: true })

// Methods
const saveAsTask = () => {
  const taskData = {
    title: taskTitle.value,
    description: taskDescription.value,
    priority: taskPriority.value,
    category: 'research',
    tags: ['research', 'agent-generated'],
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) // 1 week from now
  }
  
  emit('saveAsTask', taskData)
  showTaskForm.value = false
}

const saveAsGoal = () => {
  const goalData = {
    title: goalTitle.value,
    description: goalDescription.value,
    target: goalTarget.value,
    category: 'research',
    tags: ['research', 'agent-generated']
  }
  
  emit('saveAsGoal', goalData)
  showGoalForm.value = false
}

const copyToClipboard = async () => {
  try {
    await navigator.clipboard.writeText(props.note?.content || '')
    // You could add a toast notification here
  } catch (err) {
    console.error('Failed to copy to clipboard:', err)
  }
}

const exportToPDF = () => {
  // PDF export functionality would go here
  console.log('Exporting to PDF...')
}
</script>

<style scoped>
.prose {
  font-size: 14px;
  line-height: 1.7;
}

.prose h1, .prose h2, .prose h3, .prose h4 {
  color: #F3F4F6;
  margin-top: 1.5em;
  margin-bottom: 0.5em;
}

.prose p {
  margin-bottom: 1em;
}

.prose ul, .prose ol {
  margin-bottom: 1em;
  padding-left: 1.5em;
}

.prose li {
  margin-bottom: 0.5em;
}

.prose strong {
  color: #F9FAFB;
  font-weight: 600;
}
</style>
